version: '3.7'

services:
   zookeeper:
      image: zookeeper
      container_name: zookeeper
      restart: always
      networks:
         - storm
      environment:
         ZOO_MY_ID: 1
         ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ports:
         - "2181:2181"
         - "2888:2888"
         - "3888:3888"
      volumes:
         - zookeeper_logs:/var/log/zookeeper

   spark-master:
      image: bitnami/spark:2.4.5 
      networks:
         - storm
      restart: always
      environment:
         - SPARK_MODE=master
      ports:
         - "7077:7077"
         - "8080:8080"
      volumes:
         - sparkmaster_logs:/opt/bitnami/spark/logs

   spark-worker:
      image: bitnami/spark:2.4.5
      networks:
         - storm
      environment:
         - SPARK_MODE=worker
         - SPARK_MASTER_URL=spark://spark-master:7077
      ports:
         - "8081:8081"
      restart: always
      volumes:
         - sparkworker_logs:/opt/bitnami/spark/logs

   kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
         - "9092:9092"
      environment:
         HOSTNAME: kafka
         HOSTNAME_COMMAND: "docker info | grep 'Node Address: ' | cut -d' ' -f 5"
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         # modificacion para configurar la autenticacion y autorizacion
         KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://34.175.107.208:9092 
         KAFKA_LISTENERS: SASL_PLAINTEXT://:9092 
         KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
         KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
         KAFKA_SUPER_USERS: User:admin;User:admin2
         KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
         KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
         KAFKA_OPTS: "-Djava.security.auth.login.config=/jaas.conf"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - kafka_logs:/opt/kafka/logs
         # definicion de credenciales
         - /home/jesussaizentrepreneur/jaas.conf:/jaas.conf    
         # credenciales incorrectas para autenticacion
         - /home/jesussaizentrepreneur/client.properties:/client.properties 
         # credenciales correctas para autenticacion
         - /home/jesussaizentrepreneur/admin.properties:/admin.properties 
         # credenciales usuario1 correctas
         - /home/jesussaizentrepreneur/producer.properties:/producer.properties 
         # credenciales usuario2 correctas
         - /home/jesussaizentrepreneur/consumer.properties:/consumer.properties 
      networks:
         - storm

   cassandra:
      image: cassandra
      container_name: cassandra
      networks:
         - storm
      environment:
         CASSANDRA_BROADCAST_ADDRESS: cassandra 
         CASSANDRA_CLUSTER_NAME: POLLUTION_CLUSTER
         CASSANDRA_ENDPOIN_SNITCH: GossipingPropertyFileSnitch
         CASSANDRA_DC: dc1
         CASSANDRA_RACK: rack1
         CASSANDRA_SEEDS: cassandra
      ports:
         - "9042:9042"
      volumes:
         - cassandra_logs:/var/log/cassandra

   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
      environment:
         - discovery.type=single-node
      ports:
         - "9200:9200"
         - "9300:9300"
      networks:
         - storm

   logstash:
      image: docker.elastic.co/logstash/logstash:7.9.3
      volumes:
         # Ficheros de configuracion de Logstash
         - /home/jesussaizentrepreneur/logstash_config:/usr/share/logstash/config
         - /home/jesussaizentrepreneur/logstash_pipeline:/usr/share/logstash/pipeline
      ports:
         - "5044:5044"
      depends_on:
         - elasticsearch
      networks:
         - storm

   kibana:
      image: docker.elastic.co/kibana/kibana:7.9.3
      ports:
         - "5601:5601"
      environment:
         ELASTICSEARCH_URL: http://elasticsearch:9200
         ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      depends_on:
         - elasticsearch
      networks:
         - storm
    
   filebeat:
      image: docker.elastic.co/beats/filebeat:7.9.3
      user: root # Necesario para leer los logs de Docker
      volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        # Archivo de configuración
        - /home/jesussaizentrepreneur/filebeat.yml:/usr/share/filebeat/filebeat.yml 
        # Volumen con los logs de Kafka
        - kafka_logs:/usr/share/filebeat/kafka_logs 
      networks:
        - storm
      depends_on:
        - kafka
        - zookeeper
        #- cassandra
        - elasticsearch
        - logstash
      command: filebeat -e -strict.perms=false 

volumes:
   kafka_logs: 
     external: true
   zookeeper_logs: 
     external: true
   sparkmaster_logs: 
     external: true
   sparkworker_logs: 
     external: true
   cassandra_logs: 
     external: true


networks:
   storm:
      driver: bridge
