# elasticsearch-values.yaml
replicas: 1
minimumMasterNodes: 1

esJavaOpts: "-Xmx512m -Xms512m"

resources:
  requests:
    cpu: "250m"  
    memory: "1Gi"  
  limits:
    cpu: "500m"  
    memory: "1Gi"  

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi  

#esConfig:
  #elasticsearch.yml: |
    #xpack.security.enabled: false
    #xpack.security.transport.ssl.enabled: false
    #xpack.security.http.ssl.enabled: false

networkPolicy:
  http:
    enabled: true

#xpack.security.authc.enabled: false
